export const SEGMENTS = {
  home: "home",
  products: "products",
  microsoftCsp: "microsoft-csp",
  adobe: "adobe",
  amazonWebServices: "amazon-web-services",
  transactions: "transactions",
  insights: "insights",
  resellerAdministration: "reseller-administration",
  support: "support",
  apiIntegrations: "api-integrations",
  settings: "settings",
  previousCloudIq: "previous-cloud-iq",
  help: "help",
  termsAndConditions: "terms-and-conditions",
} as const;

export const PATHS = {
  root: "/",
  home: `/${SEGMENTS.home}`,
  products: `/${SEGMENTS.products}`,
  microsoftCsp: `/${SEGMENTS.microsoftCsp}`,
  adobe: `/${SEGMENTS.adobe}`,
  amazonWebServices: `/${SEGMENTS.amazonWebServices}`,
  transactions: `/${SEGMENTS.transactions}`,
  insights: `/${SEGMENTS.insights}`,
  resellerAdministration: `/${SEGMENTS.resellerAdministration}`,
  support: `/${SEGMENTS.support}`,
  apiIntegrations: `/${SEGMENTS.apiIntegrations}`,
  settings: `/${SEGMENTS.settings}`,
  previousCloudIq: `/${SEGMENTS.previousCloudIq}`,
  help: `/${SEGMENTS.help}`,
  termsAndConditions: `/${SEGMENTS.termsAndConditions}`,
} as const;
