sonar.projectKey=softwareone-mpt-github_ffc-extension_frontend
sonar.projectName=FinOps for Cloud Extension - Frontend
sonar.organization=softwareone-mpt-github

sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts,src/**/*.spec.tsx

sonar.exclusions=src/api/ffc-api-model/**,src/api/ffc-api-model.json,src/**/*.d.ts
sonar.coverage.exclusions=src/i18n/**,src/**/TestUtils.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPaths=tsconfig.json
