version: 1.0.0
openapi: /bypass/openapi.json
events:
  - event: platform.commerce.order.status_changed
    condition: "and(eq(status,Processing),eq(product.id,{{ settings.mpt_product_id }}))"
    path: "/events/commerce/orders"
    task: true
plugs:
  - id: "{{ settings.ui_plugs_prefix }}"
    name: Sandbox Entry{% if settings.ui_plugs_prefix != "ffc" %} ({{ settings.ui_plugs_prefix }}){% endif %}
    description: Sandbox Entry.
    icon: extension
    socket: portal
  - id: sandbox_standalone_{% if settings.ui_plugs_prefix != "ffc" %}_({{ settings.ui_plugs_prefix }}){% endif %}
    name: Sandbox Standalone{% if settings.ui_plugs_prefix != "ffc" %} ({{ settings.ui_plugs_prefix }}){% endif %}
    description: Sandbox Standalone example.
    icon: adobe.png
    socket: portal.root
    href: "/static/SandboxStandaloneRoot.js"
  - id: organizations
    name: Organizations (Single entry)
    description: Shows Sandbox view for Organisations single view.
    icon: adobe.png
    socket: portal.{{ settings.ui_plugs_prefix }}
    href: "/static/OrganizationsEntry.js"
  - id: entitlements
    name: Entitlements (Single entry)
    description: Shows Sandbox view for Entitlements single view.
    icon: adobe.png
    socket: portal.{{ settings.ui_plugs_prefix }}
    href: "/static/EntitlementsEntry.js"
  - id: finops.admin.create-entitlement-modal
    name: Sandbox Create Entitlement Modal
    description: Sandbox Modal Wizard to create a new entitlement
    icon: adobe.png
    href: "/static/CreateEntitlementModal.js"
