version: 1.0.0
openapi: /bypass/openapi.json
events:
  - event: platform.commerce.order.status_changed
    condition: "and(eq(status,Processing),eq(product.id,{{ settings.mpt_product_id }}))"
    path: "/events/commerce/orders"
    task: true
plugs:
- id: "{{ settings.ui_plugs_prefix }}"
  name: FinOps for Cloud{% if settings.ui_plugs_prefix != "ffc" %} ({{ settings.ui_plugs_prefix }}){% endif %}
  description: FinOps for Cloud
  icon: extension
  socket: portal
- id: finops_{% if settings.ui_plugs_prefix != "ffc" %}_({{ settings.ui_plugs_prefix }}){% endif %}
  name: FinOps for Cloud - Standalone {% if settings.ui_plugs_prefix != "ffc" %} ({{ settings.ui_plugs_prefix }}){% endif %}
  description: This section shows all of the customers Organisations created in FinOps.
  icon: adobe.png
  socket: portal.root
  href: "/static/index.js"
- id: organizations
  name: Organizations
  description: This section shows all of the customers Organisations created in FinOps.
  icon: adobe.png
  socket: portal.{{ settings.ui_plugs_prefix }}
  href: "/static/Organizations.js"
- id: entitlements
  name: Entitlements
  description: This section provides visibility into what services and resources of
    organizations are entitled to use.
  icon: adobe.png
  socket: portal.{{ settings.ui_plugs_prefix }}
  href: "/static/Entitlements.js"
- id: finops.admin.create-user-modal
  name: Create User Modal
  description: Wizard to create a new user
  icon: adobe.png
  href: "/static/CreateUserModal.js"
- id: finops.admin.create-entitlement-modal
  name: Create Entitlement Modal
  description: Wizard to create a new entitlement
  icon: adobe.png
  href: "/static/CreateEntitlementModal.js"
