sonar.projectKey=softwareone-platform_ffc-extension
sonar.organization=softwareone-mpt-github

sonar.language=py,ts,tsx,js,jsx

sonar.sources=backend/app,frontend/src
sonar.tests=backend/tests,frontend/src
sonar.test.inclusions=frontend/src/**/*.spec.{ts,tsx,js,jsx}
# sonar.inclusions=backend/app/**,frontend/src/**
# sonar.exclusions=backend/tests/**, backend/app/main.py, backend/app/__main__.py

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=coverage.xml
sonar.python.version=3.12

sonar.javascript.lcov.reportPaths=lcov.info
sonar.typescript.tsconfigPaths=frontend/tsconfig.json
