sonar.projectKey=softwareone-mpt-github_ffc-extension_backend
sonar.projectName=FinOps for Cloud Extension - Backend
sonar.organization=softwareone-mpt-github

sonar.sourceEncoding=UTF-8

sonar.sources=app
sonar.tests=tests

sonar.exclusions=app/main.py,app/__main__.py

sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
