"""Migrate account type

Revision ID: 1ba8d43509b6
Revises: 4e8e385293da
Create Date: 2026-04-22 13:52:21.999700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '1ba8d43509b6'
down_revision: Union[str, None] = '4e8e385293da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE accounttype ADD VALUE IF NOT EXISTS 'admin'")
    op.execute("UPDATE accounts SET type = 'admin' WHERE type = 'operations'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
