"""add account integration

Revision ID: 91e67d9ca2be
Revises: 1ba8d43509b6
Create Date: 2026-05-18 14:18:34.516937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '91e67d9ca2be'
down_revision: Union[str, None] = '1ba8d43509b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('integration', sa.Enum('aws', 'google', 'microsoft', 'softwareone', name='accountintegration'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'integration')
    # ### end Alembic commands ###
