"""add termination feedback

Revision ID: ab62a28aa5e4
Revises: 3eff35a80454
Create Date: 2026-10-09 11:21:30.132603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'ab62a28aa5e4'
down_revision: Union[str, None] = '3eff35a80454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('termination_feedbacks',
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('reason', sa.Enum('missing_features', 'too_complex', 'cost_or_pricing', 'data_accuracy', 'switching_tool', 'need_ended', 'internal_changes', 'unsatisfactory_support', 'other', name='terminationreason'), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_index(op.f('ix_termination_feedbacks_id'), 'termination_feedbacks', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_termination_feedbacks_id'), table_name='termination_feedbacks')
    op.drop_table('termination_feedbacks')
    sa.Enum(name='terminationreason').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
